apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green-new # New name to avoid selector conflict
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
        - name: my-app
          image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
        - name: my-app
          image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always