apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-app 
  template:
    metadata:
      labels:
        app: my-app  
    spec:
      containers:
      - name: my-app  
        image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:v.1.0.1 
        ports:
        - containerPort: 3000  