apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  labels:
    app: my-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-blue
  template:
    metadata:
      labels:
        app: my-app-blue
    spec:
      containers:
      - name: my-app
        image: my-app-image:v.1.0.0 # as in blue deployment we are using the same image as in the main deployment but we need to put stable version of the image
        ports:
        - containerPort: 80