apiVersion: v1
kind: Service
metadata:
  name: blue-service
  labels:
    app: my-app-blue
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app-blue