apiVersion: v1
kind: Service
metadata:
  name: green-service
  labels:
    app: my-app-green
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app-green